# Generated by Django 3.0.5 on 2020-05-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pontoturistico_endereco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='descrcao',
            new_name='descricao',
        ),
    ]
